# system_migration_tool.gd - Tool to help migrate from the old system to the new one
class_name SystemMigrationTool
extends Node

# Debug flag
const DEBUG = true

# Migration options
var enable_new_projectile_system = false
var enable_new_behavior_system = false
var replace_projectile_script = false
var replace_behavior_manager = false

# Paths and references
var projectile_script_path = "res://scripts/projectile.gd"
var new_projectile_base_path = "res://scripts/projectile_base.gd"
var behavior_manager_path = "res://scripts/behavior_manager.gd"
var new_behavior_manager_path = "res://scripts/improved_behavior_manager.gd"

func _ready():
	print("System Migration Tool initialized")
	print("Use start_migration() to begin the migration process")

# Start the migration process
func start_migration():
	print("Starting migration process...")
	print("This tool will help migrate from your old weapon system to the new refactored system.")
	
	# Check if needed files exist
	check_file_availability()
	
	# Enable new systems in project settings
	if enable_new_projectile_system:
		enable_new_systems()
	
	# Replace scripts if requested
	if replace_projectile_script:
		replace_projectile_scripts()
	
	if replace_behavior_manager:
		replace_behavior_managers()
	
	print("Migration completed!")
	print("Note: You may need to restart the engine to apply some changes.")

# Check if all needed files exist
func check_file_availability():
	print("Checking file availability...")
	
	var file_status = {
		"Old projectile script": FileAccess.file_exists(projectile_script_path),
		"New projectile base": FileAccess.file_exists(new_projectile_base_path),
		"Old behavior manager": FileAccess.file_exists(behavior_manager_path),
		"New behavior manager": FileAccess.file_exists(new_behavior_manager_path),
		"Standard projectile": FileAccess.file_exists("res://scripts/standard_projectile.gd"),
		"Homing projectile": FileAccess.file_exists("res://scripts/homing_projectile.gd"),
		"Bouncing projectile": FileAccess.file_exists("res://scripts/bouncing_projectile.gd"),
		"Explosive projectile": FileAccess.file_exists("res://scripts/explosive_projectile.gd"),
		"Wave projectile": FileAccess.file_exists("res://scripts/wave_projectile.gd"),
		"Singularity projectile": FileAccess.file_exists("res://scripts/singularity_projectile.gd"),
		"Projectile factory": FileAccess.file_exists("res://scripts/projectile_factory.gd"),
		"System adapter": FileAccess.file_exists("res://scripts/projectile_system_adapter.gd")
	}
	
	print("File status:")
	for file_name in file_status:
		print("- ", file_name, ": ", "Available" if file_status[file_name] else "MISSING")
	
	# Check if we can proceed
	var can_proceed = true
	for file_name in file_status:
		if not file_status[file_name]:
			print("WARNING: Missing required file: ", file_name)
			can_proceed = false
	
	if not can_proceed:
		print("ERROR: Cannot proceed with migration due to missing files.")
		print("Please make sure all required files are available.")
	else:
		print("All required files are available. Proceeding with migration.")

# Enable new systems in project settings
func enable_new_systems():
	print("Enabling new systems in project settings...")
	
	# Create project setting if it doesn't exist
	if not ProjectSettings.has_setting("game/use_new_projectile_system"):
		ProjectSettings.set_setting("game/use_new_projectile_system", true)
		print("Created project setting: game/use_new_projectile_system = true")
	else:
		ProjectSettings.set_setting("game/use_new_projectile_system", true)
		print("Updated project setting: game/use_new_projectile_system = true")
	
	if not ProjectSettings.has_setting("game/use_new_behavior_system"):
		ProjectSettings.set_setting("game/use_new_behavior_system", true)
		print("Created project setting: game/use_new_behavior_system = true")
	else:
		ProjectSettings.set_setting("game/use_new_behavior_system", true)
		print("Updated project setting: game/use_new_behavior_system = true")
	
	# Save the project settings
	ProjectSettings.save()
	print("Project settings saved.")

# Update old scripts to use the new system - simple adapter approach
func replace_projectile_scripts():
	print("Replacing projectile scripts...")
	
	# Create backup of the old script
	var old_script_content = FileAccess.open(projectile_script_path, FileAccess.READ).get_as_text()
	var backup_path = projectile_script_path + ".backup"
	var backup_file = FileAccess.open(backup_path, FileAccess.WRITE)
	backup_file.store_string(old_script_content)
	backup_file.close()
	print("Created backup of old projectile script at: ", backup_path)
	
	# Create adapter script that redirects to the new system
	var adapter_script = """# projectile.gd - Adapter script to bridge old code with new system
# This file was automatically generated by the system migration tool
extends CharacterBody2D

# Forward all properties to maintain compatibility
var speed = 400.0
var direction = Vector2.RIGHT
var lifetime = 1.0
var timer = 0.0
var damage = 10
var knockback = 500
var effects = []
var hit_effect = ""
var wielder_ref = null
var weapon_id = ""
var bounce_count = 0
var homing_strength = 0.0
var gravity_factor = 0.0
var piercing = 0
var explosion_radius = 0.0
var hit_targets = []
var projectile_type = "standard"

# Flag to indicate this is an adapter
var is_adapter = true

func _ready():
	# Replace self with appropriate new projectile type
	var config = {
		"speed": speed,
		"direction": direction,
		"lifetime": lifetime,
		"damage": damage,
		"knockback": knockback,
		"effects": effects,
		"hit_effect": hit_effect,
		"bounce_count": bounce_count,
		"homing_strength": homing_strength,
		"gravity_factor": gravity_factor,
		"piercing": piercing,
		"explosion_radius": explosion_radius,
		"projectile_type": projectile_type,
		"weapon_id": weapon_id
	}
	
	# Add all metadata
	for meta_key in get_meta_list():
		config[meta_key] = get_meta(meta_key)
	
	# Create appropriate projectile using the adapter
	var new_projectile = ProjectileSystemAdapter.create_projectile(config, wielder_ref)
	
	# Match position and velocity
	new_projectile.global_position = global_position
	new_projectile.velocity = velocity
	
	# Add to scene in same place
	var parent = get_parent()
	if parent:
		parent.add_child(new_projectile)
		# Remove self
		queue_free()

# Initialize function for compatibility
func initialize(config):
	# Set basic properties
	if "speed" in config:
		speed = config.speed
	if "direction" in config:
		direction = config.direction
	if "lifetime" in config:
		lifetime = config.lifetime
	if "damage" in config:
		damage = config.damage
	if "knockback" in config:
		knockback = config.knockback
	if "effects" in config:
		effects = config.effects
	if "hit_effect" in config:
		hit_effect = config.hit_effect
	if "bounce_count" in config:
		bounce_count = config.bounce_count
	if "homing_strength" in config:
		homing_strength = config.homing_strength
	if "gravity_factor" in config:
		gravity_factor = config.gravity_factor
	if "piercing" in config:
		piercing = config.piercing
	if "explosion_radius" in config:
		explosion_radius = config.explosion_radius
	if "projectile_type" in config:
		projectile_type = config.projectile_type
	if "weapon_id" in config:
		weapon_id = config.weapon_id
		set_meta("weapon_id", weapon_id)
	
	# Set initial velocity
	velocity = Vector2(direction * speed, 0) if typeof(direction) != TYPE_VECTOR2 else direction * speed
	
	return self  # Return self to allow method chaining

# Stub methods for compatibility
func destroy():
	queue_free()

func has_hit_target(target):
	return target in hit_targets

func add_hit_target(target):
	if !target in hit_targets:
		hit_targets.append(target)

func add_behavior(behavior):
	return true
"""
	
	# Write the adapter script
	var new_script_file = FileAccess.open(projectile_script_path, FileAccess.WRITE)
	new_script_file.store_string(adapter_script)
	new_script_file.close()
	print("Replaced projectile script with adapter script.")

# Replace behavior managers
func replace_behavior_managers():
	print("Replacing behavior managers...")
	
	# Create backup of the old script
	var old_script_content = FileAccess.open(behavior_manager_path, FileAccess.READ).get_as_text()
	var backup_path = behavior_manager_path + ".backup"
	var backup_file = FileAccess.open(backup_path, FileAccess.WRITE)
	backup_file.store_string(old_script_content)
	backup_file.close()
	print("Created backup of old behavior manager at: ", backup_path)
	
	# Copy the new behavior manager to the old path
	var new_script_content = FileAccess.open(new_behavior_manager_path, FileAccess.READ).get_as_text()
	var new_script_file = FileAccess.open(behavior_manager_path, FileAccess.WRITE)
	new_script_file.store_string(new_script_content)
	new_script_file.close()
	print("Replaced behavior manager with improved version.")

# Run test case to verify migration
func run_test_case():
	print("Running migration test case...")
	
	# Test creating a projectile
	var config = {
		"speed": 400.0,
		"direction": Vector2.RIGHT,
		"lifetime": 1.0,
		"damage": 10,
		"knockback": 500,
		"bounce_count": 3,
		"homing_strength": 0.5,
		"explosion_radius": 60.0
	}
	
	var projectile = ProjectileSystemAdapter.create_projectile(config, null)
	
	if projectile:
		print("Test passed! Successfully created a projectile with the new system.")
		print("Projectile type: ", projectile.get_script().resource_path)
	else:
		print("Test failed! Could not create a projectile with the new system.")
